### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by OliverKersting** [FOODy/express-webpack-boilerplate#1]
I got an error compiling the code with "npm run watch-server"

/src/server/lib/graphql/mount-graphql-middleware.ts on line 29

fieldResolver: createGraphqlFieldResolver()

TS2322: Type 'GraphQLFieldResolver<any, GraphqlContext, { [argName: string]: any; }>' is not assignable to type 'GraphQLFieldResolver<any, object, { [argName: string]: any; }>'.
  Type '{}' is missing the following properties from type 'GraphqlContext': request, pubsub
Version: typescript 3.4.2, tslint 5.15.0
Time: 2683ms

I was able to bypass the problem by adding a cast

fieldResolver: createGraphqlFieldResolver() as GraphQLFieldResolver<any,any>

**Comment by FOODy** [comment]
Fixed. Thank you!
