### ISSUE TITLE
Error occured while trying to proxy to: localhost:8082/

### ISSUE THREAD

**Issue by OliverKersting** [FOODy/express-webpack-boilerplate#2]
running `npm run watch-graphql` outputs:

> @lehrerkind/lx-shop@1.0.0 watch-graphql /Users/nobody1/Documents/lx-shop
> gql-gen -c graphql.codegen.yml -w
> 
>   ✔ Parse configuration
>   ✔ Generate outputs
>   ℹ Watching for changes...

running `npm run watch-server` outputs:

> @lehrerkind/lx-shop@1.0.0 watch-server /Users/nobody1/Documents/lx-shop
> webpack --mode=development --watch --config=build/config/webpack.server.js
> 
> clean-webpack-plugin: /Users/nobody1/Documents/lx-shop/dist/development/app has been removed.
> Starting type checking and linting service...
> Using 1 worker with 2048MB memory limit
> 
> webpack is watching the files…
> 
> Type checking and linting in progress...
> Built at: 06/28/2019 7:52:40 PM
> Entrypoint main = index.js
> No type errors found
> No lint errors found
> Version: typescript 3.5.1, tslint 5.17.0
> Time: 3055ms

running `npm run watch-browser` outputs:

> @lehrerkind/lx-shop@1.0.0 watch-browser /Users/nobody1/Documents/lx-shop
> node -r dotenv/config build/scripts/watch-browser.js
> 
> clean-webpack-plugin: /Users/nobody1/Documents/lx-shop/dist/development/public has been removed.
> Starting type checking and linting service...
> Using 1 worker with 2048MB memory limit
> [HPM] Proxy created: /  ->  http://localhost:8081
> *******************************************************
> Webpack Dev Server started!
> Listening: http://localhost:8082
> *******************************************************
> No type errors found
> No lint errors found
> Version: typescript 3.5.1, tslint 5.17.0
> Time: 2062ms
> webpack built d9d5026ccf1c11307524 in 2378ms
> ℹ ｢wdm｣: Hash: d9d5026ccf1c11307524
> Version: webpack 4.32.2
> Time: 2378ms
> Built at: 06/28/2019 8:03:26 PM
>                                Asset       Size        Chunks                    Chunk Names
>                           index.html  312 bytes                [emitted]         
>         main.d9d5026ccf1c11307524.js   37.5 KiB          main  [emitted]         main
> vendors~main.d9d5026ccf1c11307524.js   3.95 MiB  vendors~main  [emitted]  [big]  vendors~main
> Entrypoint main [big] = vendors~main.d9d5026ccf1c11307524.js main.d9d5026ccf1c11307524.js
> [0] multi ./src/browser/index.tsx webpack-hot-middleware/client 40 bytes {main} [built]
> [./node_modules/ansi-html/index.js] 4.16 KiB {vendors~main} [built]
> [./node_modules/html-entities/index.js] 231 bytes {vendors~main} [built]
> [./node_modules/react-dom/cjs/react-dom.development.js] 768 KiB {vendors~main} [built]
> [./node_modules/react-dom/index.js] 1.33 KiB {vendors~main} [built]
> [./node_modules/react/cjs/react.development.js] 62.3 KiB {vendors~main} [built]
> [./node_modules/react/index.js] 190 bytes {vendors~main} [built]
> [./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.17 KiB {vendors~main} [built]
> [./node_modules/webpack-hot-middleware/client.js] (webpack)-hot-middleware/client.js 7.68 KiB {vendors~main} [built]
> [./node_modules/webpack-hot-middleware/node_modules/strip-ansi/index.js] (webpack)-hot-middleware/node_modules/strip-ansi/index.js 161 bytes {vendors~main} [built]
> [./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {vendors~main} [built]
> [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
> [./src/browser/app.tsx] 138 bytes {main} [built]
> [./src/browser/index.tsx] 311 bytes {main} [built]
> [./src/browser/polyfills.ts] 29 bytes {main} [built]
>     + 496 hidden modules
> Child html-webpack-plugin for "index.html":
>          Asset      Size  Chunks  Chunk Names
>     index.html  1.38 MiB       0  
>     Entrypoint undefined = index.html
>     [./node_modules/html-webpack-plugin/lib/loader.js!./src/browser/index.html] 344 bytes {0} [built]
>     [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
>     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
>     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
> ℹ ｢wdm｣: Compiled successfully.

Opening `http://localhost:8082` gets me the message (in the browser and vs-code):

> Error occured while trying to proxy to: localhost:8082/

I work on macOS.

**Comment by OliverKersting** [comment]
I get the same error on Win10

**Comment by FOODy** [comment]
Did you run `npm run start`?
Seems like the Backend is not running or crashes.

**Comment by OliverKersting** [comment]
When I run `npm run start` I get the 'hello world'-page. Seems like it's working.
But the vs-code-console constantly prints out the following error:

> Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
>   errno: 'ECONNREFUSED',
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 6379 

But the app is running fine...

**Comment by FOODy** [comment]
The error means that the connection to the redis server cannot be established.

Redis is used for the session store and the graphql subscriptions.

If you don't want to install redis you can do the following changes:
*(not recommended for production)*

1. Use the session file store
	Install dependencies
	```
	npm install session-file-store
	npm install -D @types/session-file-store
	```

	Edit `src/server/lib/session/create-session-store.ts`:
	```ts
	import session, {MemoryStore, Store} from 'express-session';
	import sessionFileStoreFactory from 'session-file-store';

	export default function createSessionStore(): Store | MemoryStore {
	  const FileStore = sessionFileStoreFactory(session);

	  return new FileStore();
	}
	```

2. Use the in-memory PubSubEngine for the graphql subscriptions

	Edit `src/server/lib/graphql/create-graphql-pub-sub.ts`:
	```ts
	import {PubSub, PubSubEngine} from 'graphql-subscriptions';

	export default function createGraphqlPubSub(): PubSubEngine {
	  return new PubSub();
	}
	```

**Comment by OliverKersting** [comment]
I successfully run `npm install redis`.

(Also tired `npm install -g redis`)

But I keep getting the error message. Do I have to do some kind of configuration or something?

**Comment by FOODy** [comment]
With `npm install redis` you only installed a redis client.
You have to install the redis server. (https://redis.io/)

The easiest way to install redis on windows would be via Docker.
(https://docs.docker.com/docker-for-windows/install/ and https://hub.docker.com/_/redis/)
```
$ docker run --name redis -d redis
```

**Comment by OliverKersting** [comment]
I installed redis via terminal and started the server.

Now I'm getting no more errors...

Thank you so much!!
